### ISSUE TITLE
This plugin is amazing! But the Email API Keys is an empty page.

### ISSUE THREAD

**Issue by fintechee** [1FF/mautic-custom-email-settings#8]
Hi Team,

Many thanks for providing such a good stuff.
This plugin is amazing!

But the Email API Keys page displayed just blank after I configured the email setting.
I followed all the steps including clear the cache.

My PHP is 8.0.
Mautic is 4.4.10.

How to fix it?
Thank you.

**Comment by insssomniac** [comment]
Hi @fintechee,
It seems it is because you have fresh Mautic installation and didn't created any emails yet. Because the plugin set a custom key and provider for each email.
Please try to create one or two emails and let me know if it's working.

**Comment by fintechee** [comment]
Hi @insssomniac

Thank you for your reply!!
It works now!
It doesn't support self-hosted SMTP currently, right?

**Comment by insssomniac** [comment]
Yes, only Sendgrid and Sparkpost at the moment

**Comment by insssomniac** [comment]
Alright then, I'm glad it works, then I'll close it

**Comment by insssomniac** [comment]
Alright then, I'm glad it works, then I'll close it

**Comment by fintechee** [comment]
Thank you for your help!
